name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v2

      - name: Build
        run: go build ./...

      - name: Release
        uses: goreleaser/goreleaser-action@v0.145.0
